export const INCREMENT = 'INCREMENT';

export const CONNECTED_TO = 'CONNECTED_TO';
export const WIFI_STATUS = 'WIFI_STATUS';

export const CONNECT_TO_WIFI = 'CONNECT_TO_WIFI';
export const CONNECT_TO_WIFI_SUCCESS = 'CONNECT_TO_WIFI_SUCCESS';
export const CONNECT_TO_WIFI_FAILURE = 'CONNECT_TO_WIFI_FAILURE';
export const SAVE_FENCING = 'SAVE_FENCING';
export const SAVE_FENCING_SUCCESS = 'SAVE_FENCING_SUCCESS';
export const SAVE_FENCING_FAILURE = 'SAVE_FENCING_FAILURE';

export const GET_ROBOT_LOCATION = 'GET_ROBOT_LOCATION';
export const GET_ROBOT_LOCATION_SUCCESS = 'GET_ROBOT_LOCATION_SUCCESS';
export const GET_ROBOT_LOCATION_FAILURE = 'GET_ROBOT_LOCATION_FAILURE';
export const GET_ROBOTS = 'GET_ROBOTS';
export const GET_ROBOTS_SUCCESS = 'GET_ROBOTS_SUCCESS';
export const GET_ROBOTS_FAILURE = 'GET_ROBOTS_FAILURE';
export const SET_ROBOT_DATA = 'SET_ROBOT_DATA';
export const SET_ROBOT_DATA_SUCCESS = 'SET_ROBOT_DATA_SUCCESS';
export const SET_ROBOT_DATA_FAILURE = 'SET_ROBOT_DATA_FAILURE';

export const SET_CLEANING_DATA = 'SET_CLEANING_DATA';
export const SET_CLEANING_DATA_SUCCESS = 'SET_CLEANING_DATA_SUCCESS';
export const SET_CLEANING_DATA_FAILURE = 'SET_CLEANING_DATA_FAILURE';

export const SET_SAVE_SCHEDULE = 'SET_SAVE_SCHEDULE';
export const DELETE_SCHEDULE = 'DELETE_SCHEDULE';

export const SET_ONBOARDING = 'SET_ONBOARDING';
