export const INCREMENT = 'INCREMENT';

export const CONNECTED_TO = 'CONNECTED_TO';
export const WIFI_STATUS = 'WIFI_STATUS';

export const CONNECT_TO_WIFI = 'CONNECT_TO_WIFI';
export const CONNECT_TO_WIFI_SUCCESS = 'CONNECT_TO_WIFI_SUCCESS';
export const CONNECT_TO_WIFI_FAILURE = 'CONNECT_TO_WIFI_FAILURE';