export const INCREMENT = 'INCREMENT';

export const CONNECTED_TO = 'CONNECTED_TO';
export const WIFI_STATUS = 'WIFI_STATUS';

export const CONNECT_TO_WIFI = 'CONNECT_TO_WIFI';
export const CONNECT_TO_WIFI_SUCCESS = 'CONNECT_TO_WIFI_SUCCESS';
export const CONNECT_TO_WIFI_FAILURE = 'CONNECT_TO_WIFI_FAILURE';
export const SAVE_FENCING = 'SAVE_FENCING';
export const SAVE_FENCING_SUCCESS = 'SAVE_FENCING_SUCCESS';
export const SAVE_FENCING_FAILURE = 'SAVE_FENCING_FAILURE';

export const GET_ROBOT_LOCATION = 'GET_ROBOT_LOCATION';
export const GET_ROBOT_LOCATION_SUCCESS = 'GET_ROBOT_LOCATION_SUCCESS';
export const GET_ROBOT_LOCATION_FAILURE = 'GET_ROBOT_LOCATION_FAILURE';
